### ISSUE TITLE
Add page for WordPress/PHP coding standards

### ISSUE THREAD

**Issue by davisshaver** [fusioneng/tech-docs#59]
We should have a place for standards like this. https://github.com/fusioneng/fusion-theme/pull/2713#issuecomment-98699959 Probably can get most of the way there by linking to VIP coding standards.

**Comment by danielbachhuber** [comment]
See also https://make.wordpress.org/core/handbook/coding-standards/php/#indentation

Once we finally get WPCS hooked up, it will be much easier to auto-flag.
