### ISSUE TITLE
Add note about 'how to contact us' to how we hire

### ISSUE THREAD

**Issue by davisshaver** [fusioneng/tech-docs#92]
[How we hire](https://github.com/fusioneng/tech-docs/blob/master/team-culture/how-we-hire.md) doesn't mention _how_ to start conversations with us, only how to submit the pre-app form. Let's fix that.

**Comment by danielbachhuber** [comment]
As should #79, as should each of our job descriptions (which I started adding a2450220623821a0703793caf4f39b8d21bee585)

**Comment by davisshaver** [comment]
:heavy_check_mark:
